### ISSUE TITLE
关卡理智花费

### ISSUE THREAD

**Issue by LittleNightmare** [Perfare/ArknightsGameData#2]
没有找到，level里是敌人和地图数据，对比obt/weekly/fly的相关数据，推测为空中威胁，但没有找到理智花费，另一个Excel全翻了，是没有理智花费吗

**Comment by cyf-gh** [comment]
搜索关键字ap也没有找到任何信息。

**Comment by cyf-gh** [comment]
已解决，在stage_table.json下，apCost键。

**Comment by cyf-gh** [comment]
fixed
