### ISSUE TITLE
可否协助解密角色小人的动作数据(.skel)文件?

### ISSUE THREAD

**Issue by KuhaQueen** [Perfare/ArknightsGameData#6]
Assets Studio可以解压到干员小人与敌方小人的的.atlas和.skel文件, 然而.skel文件是加密的.

**Comment by Kengxxiao** [comment]
skel文件不是加密的。。 只不过是SkeletonBinary格式而不是json C#版本的spine运行环境里有关于如何解析SkeletonBinary的类

**Comment by Perfare** [comment]
正如@Kengxxiao 所说，.skel只是现在spine常用的binary格式，各运行库都能直接读取
转换成json的项目github上也有很多，比如这个https://github.com/azurlane-doujin/AzurLaneSpineCharacterDecoder
另外贴个朋友写的程序，可以查看和导出动画gif https://github.com/kiletw/SpineViewerWPF
